### ISSUE TITLE
Cannot accept cookie policy anymore.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/fabric-portal#188]
Something isn't working on chrome. When I try logging in, it is asking me to accept the cookie policy, but the bar at the bottom isn't there. So I can't login. This happens only on Chrome. Firefox is fine.

**Comment by yaxue1123** [comment]
Hi Mina, 

Thanks a lot for telling us this issue! I have updated the way how portal deals with cookie-policy cookie and this issue should have been solved. To get a fresh start with portal in your Chrome, please [clear cookies in your browser ](https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop)and try again. 

Sorry for the inconvenience this issue brought to you and thanks again for your time!

Yaxue
