### ISSUE TITLE
Search for projects by project ID

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/fabric-portal#189]
We should add the ability to search for projects by their project id.  

I'm seeing requests for permission tags where the users ask for tag X, on project id Y.  Currently, there is no way for me to find their project using the project id.

**Comment by yaxue1123** [comment]
Hi Paul,

Thanks for your feedback! The "search-by-project-id" has been enabled in portal. You need select “ID” from the dropdown list on the left of search box then paste the project uuid to search.

![Projects Page](https://user-images.githubusercontent.com/37635744/174679373-c4441273-4fa3-4706-8083-3b415d5749bc.png)

Additionally, a **Copy** button is added near project id field on the project detail page for user to copy id more easily.

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/37635744/174680041-e1cfcd08-d80b-46eb-a32c-ea8f3e01aaf6.png">

Yaxue
