### ISSUE TITLE
Last Minute Fixes for 1.3

### ISSUE THREAD

**Issue by yaxue1123** [fabric-testbed/fabric-portal#209]
- [x] User Profile -> My Profile: change `pronouns` field from dropdown select to free text area (since there are like 20 different things that people use as pronouns);
- [x] Experiments -> Manage Tokens: modify CM cpp to avoid using /whoami call to decide users' auth status (use the auth cookie `fabric-service-xxx-cm` instead;
- [x] Project Form: 1. change 'Project Tags' to 'Project Permissions'/ change 'No tag' to 'No permissions assigned'; 2. Move `Update PO/PM` button at the bottom of po/ pm table; 3. Allow PO to update project;
- [x] Add units `GB` for RAM and Disk/ Change `Core` to `Cores` on Resources page (two resource tables) and slice viewer.
- [x] For project members requesting a private project's data, the response is missing `project_owners` and `project_members` fields.

**Comment by ibaldin** [comment]
- The project view when a project has no tags it says 'No tag', should be plural 'No tags' or may be 'No tags assigned'
- Update project members button is above the field with project members? Seems counter intuitive - why not place it below?
- Allow PO to edit project description and visibility
- Something strange with test on beta 2 project - owners are me, Paul and Yaxue, but Yaxue is also listed as project member. Are owners listed as members? Seems the behavior is inconsistent.

**Comment by ibaldin** [comment]
- I thought we had agreed to list units for RAM and Disk in resource views. The 'Resources' view doesn't.  Isee that it is done in the slice builder though
