### ISSUE TITLE
Make site selection list searchable and alphabetically sorted in Slice Builder

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/fabric-portal#267]
Sites are not listed alphabetically in the pull down - hard to look for them. 
![Screen Shot 2023-05-30 at 1 26 45 PM](https://github.com/fabric-testbed/fabric-portal/assets/12304033/28cb6e7e-05ef-48be-af87-6b4cd58571c2)

- [x] Sort the parsed Sites alphabetically. 
- [x] Update the selection list to be with a search box (the site list could be long and it's hard for users to scroll and find a certain site).

**Comment by yaxue1123** [comment]
![image](https://github.com/fabric-testbed/fabric-portal/assets/37635744/79c01d40-4521-42a2-b0f9-260d9e2797cd)

The site list has been updated as alphabetically by default and also searchable.
