### ISSUE TITLE
Portal errors if a user is not in a project

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/fabric-portal#67]
A user who is not in a projects sees many errors in the portal. These error make sense because the portal is looking for information that does not exist.  

However, these error are confusing to the user. I think this should be limited to a single error that is intuitive to understand and persistent in the user's portal view.    Maybe there should be a persistent box that states the user has limited access/functionality because they are not in a project. This box should include instructions on how to remedy the situation.  Maybe it has a link to the "other projects" with the suggestion that they could request access to a project that they are associated with.

**Comment by yaxue1123** [comment]
PR and UIS services have addressed the issue for newly signup users and will no longer generate API error for users who don't have a project.
