### ISSUE TITLE
Confusion with Fabric Portal Global Roles

### ISSUE THREAD

**Issue by mwhicks-dev** [fabric-testbed/fabric-portal#68]
In the Roles under User Profile, the display is a little confusing if you do not have any roles (so that it is all X's as attached below). Should consider a default role/permission/etc that all users have so something is automatically checked and it is easier to understand.

![image](https://user-images.githubusercontent.com/63812007/120845437-d3fab800-c53e-11eb-8aec-520f4733df6b.png)

**Comment by yaxue1123** [comment]
- Added tooltips for "Project Lead" and "Facility Operator" to let users hover and see the explanation of these two roles;
- Changed the red cross icons to stand "No" to ban icons, which reduces confusion when there is no comparison with the green check mark.
