### ISSUE TITLE
Portal Dropdowns

### ISSUE THREAD

**Issue by paul-ruth** [fabric-testbed/fabric-portal#86]
- The jupyter link should be in a more prominent place on the portal. 
- More generally, we should think about the drop links to organize the structure of the portal. For example, all "experiments" are related to a specific project. Should the experiments tab be under "projects"?

**Comment by yaxue1123** [comment]
- We decided to keep "JupyterHub" as the second sub-menu item of "Links", underneath the "Knowledge Base";
- The "Experiments" will still be an independent menu item, but the experiment page will be divided into three sections: "My Slices", "Manage Tokens" and "Manage SSH Keys".

![image](https://user-images.githubusercontent.com/37635744/132901703-bb81788f-ee82-400f-8dbf-b1f07da2bf91.png)
